Algoritmo "semnome"
//ler numeros inteiros enquanto for diferente de 0
//se for zero, final somar valores digitados



Var

soma, numero: inteiro

Inicio


      escreva("Digite o primeiro número:")
      leia(numero)
      
      enquanto numero <> 0 faca
               escreval("Digite outro número:")
               leia(numero)
               soma <- + numero
      fimenquanto


Fimalgoritmo