Algoritmo "teste_Enquanto"
//ler numeros inteiros enquanto for diferente de 0
//se for zero, final somar valores digitados



Var

soma, numero: inteiro

Inicio


      escreva("Digite o primeiro número:")
      leia(numero)
      
      enquanto numero <> 0 faca
               soma <- soma + numero
               escreval("Digite outro número:")
               leia(numero)
      fimenquanto
      
      escreval("Soma dos números digitados: ",soma)


Fimalgoritmo